version: "2.0"

services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  configserver:
    image: steeltoeoss/config-server
    restart: always
    ports:
      - "8888:8888"
    volumes: 
      - ../config:/config
  eureka:
    image: steeltoeoss/eurekaserver
    ports:
      - "8761:8761"
    platform: linux