version: "3.0"

services:
  config-server:
    #image: hyness/spring-cloud-config-server
    image: steeltoeoss/config-server
    restart: always
    ports:
      - "8888:8888"
    volumes: 
      - ../config/:/config
    environment:
      #SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/tanzu-solutions-engineering/funny-quotes-config
      #SPRING_PROFILES_ACTIVE: git
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: /config
      SPRING_PROFILES_ACTIVE: native

  eureka:
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"

  hystrix:
    #image: kennedyoliveira/hystrix-dashboard
    image: steeltoeoss/hystrix-dashboard
    ports:
      - "7979:7979"

  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 8084:15672
      - 15672:15672
      - 5672:5672
      
  mysql:
     image: mysql:5.7
     volumes:
       - ./data/mysql:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - mysql
    environment:
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=
    restart: always
    ports:
     - 8083:80
    volumes:
     - /sessions
      
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411


volumes:
  mySqlData: