Logging:
  LogLevel:
    Default: Information
MySql:
  Client:
    Server: localhost
    Database: funny-quotes
    Username: root
    Password: ""
Management:
  Endpoints:
    Actuator:
      Exposure:
        Include: ["*"]