Spring:
  Cloud:
    Config:
      ValidateCertificates: false
Logging:
  IncludeScopes: true
  LogLevel:
    Default: Information
    Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher: None
Eureka:
  Client:
    ValidateCertificates: false
  Instance:
    HostName: localhost
Security:
  Oauth2:
    Client:
      ValidateCertificates: false
Management:
  Endpoints:
    CloudFoundry:
      ValidateCertificates: false
  Tracing:
    Exporter:
      Zipkin:
        UseShortTraceIds: true
        AlwaysSample: true
        ValidateCertificates: false
        Endpoint: http://localhost:9411/api/v2/spans
#  Metrics:
#    Exporter:
#      CloudFoundry:
#        ValidateCertificates: false

FunnyQuotes:
  EnableSecurity: false
  FailedMessage: Failure is not an option -- it comes bundled with Windows.