Spring:
  Application:
    Name: FunnyQuotesUIForms
Eureka:
  Client:
    HealthMonitoredApps: FunnyQuotesOwinWindowsService,FunnyQuotesLegacyService
    ShouldRegisterWithEureka: false
    ValidateCertificates: false
    ShouldRegisterWithEureka: false
    ValidateCertificates: false
FunnyQuotes:
  ClientType: wcf